# Generated by Django 5.2.12 on 2026-03-27 16:22

import encrypted_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_mymodel_id_alter_mymodel2_id_alter_mymodel3_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', encrypted_field.fields.EncryptedField()),
            ],
        ),
    ]
